---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gomzevfh/public_html/developments.gomze.co.za/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R revolution $DEPLOYPATH
    - /bin/cp -R sass $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp elements.html $DEPLOYPATH
    - /bin/cp icons.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp portfolio-gallery.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
    - /bin/cp -R 'upscaled images' $DEPLOYPATH
    - /bin/cp logo_white.png $DEPLOYPATH
    - rsync -av --exclude='.git' ./ $DEPLOYPATH
